/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Usuario
 */
public class IUVistaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IUVistaPrincipal.class.getName());

    /**
     * Creates new form IUVistaPrincipal
     */
    public IUVistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuAutomovil = new javax.swing.JMenuItem();
        jMenuVendedor = new javax.swing.JMenuItem();
        jMenuCliente = new javax.swing.JMenuItem();
        jMenuMetodoPago = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuMarca = new javax.swing.JMenuItem();
        jMenuTipoMotor = new javax.swing.JMenuItem();
        jMenuModelo = new javax.swing.JMenuItem();
        jMenuColor = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuRegistroVenta = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuVentasVendedor = new javax.swing.JMenuItem();
        jMenuBuscarVendedor = new javax.swing.JMenuItem();
        jMenuVendedorMayorVenta = new javax.swing.JMenuItem();
        jMenuVentaCredito = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menú Principal");

        jMenu1.setText("Gestión");

        jMenuAutomovil.setText("Automóvil");
        jMenuAutomovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAutomovilActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuAutomovil);

        jMenuVendedor.setText("Vendedor");
        jMenuVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVendedorActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuVendedor);

        jMenuCliente.setText("Cliente");
        jMenu1.add(jMenuCliente);

        jMenuMetodoPago.setText("Método de pago");
        jMenu1.add(jMenuMetodoPago);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cátalogo");

        jMenuMarca.setText("Marca");
        jMenu2.add(jMenuMarca);

        jMenuTipoMotor.setText("Tipo de Motor");
        jMenu2.add(jMenuTipoMotor);

        jMenuModelo.setText("Modelo");
        jMenu2.add(jMenuModelo);

        jMenuColor.setText("Color");
        jMenu2.add(jMenuColor);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ventas");

        jMenuRegistroVenta.setText("Registrar venta");
        jMenu3.add(jMenuRegistroVenta);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Informes y consultas");

        jMenuVentasVendedor.setText("Ventas por vendedor");
        jMenu4.add(jMenuVentasVendedor);

        jMenuBuscarVendedor.setText("Buscar vendedor");
        jMenu4.add(jMenuBuscarVendedor);

        jMenuVendedorMayorVenta.setText("Vendedor con mayor venta");
        jMenu4.add(jMenuVendedorMayorVenta);

        jMenuVentaCredito.setText("Ventas por crédito de concesionario");
        jMenu4.add(jMenuVentaCredito);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuAutomovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAutomovilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuAutomovilActionPerformed

    private void jMenuVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuVendedorActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    public javax.swing.JMenuItem jMenuAutomovil;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuBuscarVendedor;
    public javax.swing.JMenuItem jMenuCliente;
    public javax.swing.JMenuItem jMenuColor;
    public javax.swing.JMenuItem jMenuMarca;
    public javax.swing.JMenuItem jMenuMetodoPago;
    public javax.swing.JMenuItem jMenuModelo;
    public javax.swing.JMenuItem jMenuRegistroVenta;
    public javax.swing.JMenuItem jMenuTipoMotor;
    public javax.swing.JMenuItem jMenuVendedor;
    public javax.swing.JMenuItem jMenuVendedorMayorVenta;
    public javax.swing.JMenuItem jMenuVentaCredito;
    public javax.swing.JMenuItem jMenuVentasVendedor;
    // End of variables declaration//GEN-END:variables
}
